### ISSUE TITLE
[SLUS_206.22] Silent Hill 3

### ISSUE THREAD

**Issue by Cuther** [rickgaiser/neutrino#30] opened 2024-07-01 12:29 UTC
Gets stuck at the first "Silent Hill 3" screen when you just boot the game. It works perfectly in the latest version of opl tho.
This used to happen in old versiones of opl.
Game is running over USB

**Comment by rickgaiser** [comment] 2024-07-13 11:21
I can confirm this issue.

UDPBD with PS2 - works
HDD with PCSX2 - works
USB with PCSX2 - works
USB with PS2 - freezes on the Silent Hill 3 logo

This game does not load/use USB, so it's trange that only USB seems to be an issue.

**Comment by rickgaiser** [comment] 2024-09-16 05:54
Thanks for reminding me. This got fixed in c8c265f.

**Closed by rickgaiser** 2024-09-16 05:54 UTC
Labels: bug confirmed
