### ISSUE TITLE
[SLES_548.38] Donkey Xote black screen with ATA HDD

### ISSUE THREAD

**Issue by azu-pl** [rickgaiser/neutrino#43] opened 2024-10-22 08:21 UTC
Game don't start with exFAT ata HDD. I tried every compatibility mode and some combinations but game only shows a black screen.

**Comment by rickgaiser** [comment] 2024-10-23 05:27
I will test this when I get the chance.

**Comment by rickgaiser** [comment] 2024-11-13 13:02
> How is it possible that this game doesn't work in Neutrino but works in OPL?

Good question. Neutrino should have at least OPL compatibility, so this is a bug I'll be investigating for sure.

**Comment by rickgaiser** [comment] 2024-11-24 18:07
After some more investigation this game seems a problematic one to run, but also not much (or old) into available:
- ESR not working [link](https://docs.google.com/spreadsheets/d/1miGxCSbSeojY4NTIK52173judAthddJbMaPyeHfs3e8/edit?gid=0#gid=0)
- Free HDLoader not working [link](https://docs.google.com/spreadsheets/d/1_hAbXDUW0eS_H0dQo2z9buMx_oHE6eaV0BpS-FoZSn0/edit?gid=0#gid=0)
- OPL 0.9.3 needing mode "32" [link](https://psxtools.de/forum/index.php?thread/22969-release-open-ps2loader-v-0-9-3/&pageNo=39)

Other than that I could not find any info on this game. I tried OPL 2156 USB and indeed that boots the game, even without any compatibility mode.

Testing neutrino versions I can get this game to boot using version 1.0 from USB. I can also get this game to boot on the latest neutrino by reverting https://github.com/rickgaiser/neutrino/commit/c53eeb4b78265e9922784f6cabc76a0150850501, AND enabling debugging on the fakemod iop module. So this makes me think this game is somehow sensitive to where it is loaded in IOP RAM, or where the emulation modules are loaded into IOP RAM.

No solution so far, but at least a direction to look into.

**Comment by rickgaiser** [comment] 2024-11-24 21:47
I found the root cause of the issue with this game: a bug in the game itself!

The game allocates a 73984 byte buffer that **overflows** by 32 bytes. Depending on what is on that location this will cause random issues or no issues at all. The 32 bytes are overridden with zeroes, not even data.

The faulty module seems to be `RTFSSIOP.IRX`, but I cannot be 100% sure this module is the one making the allocation and the overflow, I only see this buffer being allocated directly after that module is loaded, so I assume it's that one, plus it's a custom module from the game studio.

If this module is used by other games as well they may suffer the same random issues. So if anyone knows how to track tris module in other games that would be very helpfull.

Working on a fix/workaround

**Comment by rickgaiser** [comment] 2024-11-26 20:29
Fixed in the latest version by enabling compatibility mode '7'. `-gc=7`

**Closed by rickgaiser** 2024-11-26 20:29 UTC
Labels: bug confirmed
